name: Zola Build and Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:

# --- AJOUT INDISPENSABLE ---
permissions:
  contents: write
# ---------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Install Zola and Build'
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: app/sites/rapport-projet
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VERSION: 0.19.1